import React, { useState, useCallback } from 'react';
import {
  View, Text, ScrollView, StyleSheet, Pressable,
  ActivityIndicator, Share, RefreshControl,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialIcons } from '@expo/vector-icons';
import { useRouter, useFocusEffect } from 'expo-router';
import { academyService } from '@/services/academyService';
import { colors, spacing, typography, borderRadius } from '@/constants/theme';

const PRICE_PER_PLAYER = 550; // PKR
const CURRENCY = 'PKR';
const CURRENCY_SYMBOL = '₨';

function formatNumber(n: number) {
  return n.toLocaleString('en-PK');
}

function getMonthLabel() {
  return new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
}

interface AuditData {
  academies: number;
  players: number;
  coaches: number;
  totalMembers: number;
  perAcademy: Array<{ id: string; name: string; players: number; coaches: number }>;
}

export default function AcademyAuditScreen() {
  const router = useRouter();
  const [data, setData] = useState<AuditData | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    const { data: d } = await academyService.getMonthlyAuditData();
    setData(d);
    setLoading(false);
  }, []);

  useFocusEffect(useCallback(() => { load(); }, [load]));

  const onRefresh = async () => {
    setRefreshing(true);
    await load();
    setRefreshing(false);
  };

  const totalRevenue = data ? data.players * PRICE_PER_PLAYER : 0;

  const handleShare = async () => {
    if (!data) return;
    const lines = [
      `📊 BAT BETTER 365 — Monthly Audit Report`,
      `Period: ${getMonthLabel()}`,
      ``,
      `▸ Active Academies:     ${data.academies}`,
      `▸ Total Coaches:        ${data.coaches}`,
      `▸ Total Licensed Players: ${data.players}`,
      `▸ Total Members:        ${data.totalMembers}`,
      ``,
      `💰 Revenue Summary`,
      `▸ Price Per Player:     ${CURRENCY_SYMBOL}${formatNumber(PRICE_PER_PLAYER)} ${CURRENCY}/month`,
      `▸ Total Revenue Owed:   ${CURRENCY_SYMBOL}${formatNumber(totalRevenue)} ${CURRENCY}`,
      ``,
      `📋 Per Academy Breakdown`,
      ...data.perAcademy.map((a, i) =>
        `${i + 1}. ${a.name}\n   Players: ${a.players} · Coaches: ${a.coaches} · Revenue: ${CURRENCY_SYMBOL}${formatNumber(a.players * PRICE_PER_PLAYER)} ${CURRENCY}`
      ),
      ``,
      `Generated by Bat Better 365 Admin`,
    ];
    await Share.share({ message: lines.join('\n') });
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container} edges={['top']}>
        <View style={styles.header}>
          <Pressable onPress={() => router.back()} style={styles.backBtn}>
            <MaterialIcons name="arrow-back" size={24} color={colors.text} />
          </Pressable>
          <Text style={styles.headerTitle}>Monthly Audit</Text>
          <View style={{ width: 40 }} />
        </View>
        <View style={styles.centered}><ActivityIndicator size="large" color={colors.primary} /></View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <MaterialIcons name="arrow-back" size={24} color={colors.text} />
        </Pressable>
        <Text style={styles.headerTitle}>Monthly Audit</Text>
        <Pressable style={styles.shareBtn} onPress={handleShare}>
          <MaterialIcons name="share" size={22} color={colors.primary} />
        </Pressable>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.primary} />}
      >
        {/* Period Banner */}
        <View style={styles.periodBanner}>
          <MaterialIcons name="calendar-month" size={18} color={colors.textLight} />
          <Text style={styles.periodText}>{getMonthLabel()} Report</Text>
        </View>

        {/* Revenue Hero */}
        <View style={styles.revenueCard}>
          <Text style={styles.revenueLabel}>Total Revenue Owed</Text>
          <Text style={styles.revenueAmount}>
            {CURRENCY_SYMBOL}{formatNumber(totalRevenue)}
          </Text>
          <Text style={styles.revenueSub}>{CURRENCY} per month</Text>
          <View style={styles.revenueDivider} />
          <View style={styles.revenueFormula}>
            <Text style={styles.revenueFormulaText}>
              {data?.players ?? 0} players × {CURRENCY_SYMBOL}{formatNumber(PRICE_PER_PLAYER)} {CURRENCY}
            </Text>
          </View>
        </View>

        {/* Summary Stats */}
        <View style={styles.statsRow}>
          <View style={[styles.statCard, { backgroundColor: colors.primary + '15' }]}>
            <MaterialIcons name="shield" size={24} color={colors.primary} />
            <Text style={[styles.statNumber, { color: colors.primary }]}>{data?.academies ?? 0}</Text>
            <Text style={styles.statLabel}>Active{'\n'}Academies</Text>
          </View>
          <View style={[styles.statCard, { backgroundColor: colors.success + '15' }]}>
            <MaterialIcons name="people" size={24} color={colors.success} />
            <Text style={[styles.statNumber, { color: colors.success }]}>{data?.players ?? 0}</Text>
            <Text style={styles.statLabel}>Licensed{'\n'}Players</Text>
          </View>
          <View style={[styles.statCard, { backgroundColor: colors.warning + '15' }]}>
            <MaterialIcons name="sports" size={24} color={colors.warning} />
            <Text style={[styles.statNumber, { color: colors.warning }]}>{data?.coaches ?? 0}</Text>
            <Text style={styles.statLabel}>Active{'\n'}Coaches</Text>
          </View>
        </View>

        {/* Device Lock Notice */}
        <View style={styles.lockCard}>
          <MaterialIcons name="phonelink-lock" size={20} color={colors.primary} />
          <View style={{ flex: 1 }}>
            <Text style={styles.lockTitle}>Device-Locked · Active-Only Billing</Text>
            <Text style={styles.lockSub}>
              Each player is device-locked (1 device = 1 player). Only <Text style={{ fontWeight: '800', color: colors.primary }}>Active</Text> players count toward revenue. Coaches deactivate players who have left the academy, removing them from next month's billing instantly.
            </Text>
          </View>
        </View>

        {/* Per-Academy Breakdown */}
        <View style={styles.sectionHeader}>
          <MaterialIcons name="list-alt" size={16} color={colors.text} />
          <Text style={styles.sectionTitle}>Per Academy Breakdown</Text>
        </View>

        {(data?.perAcademy ?? []).length === 0 && (
          <View style={styles.emptyCard}>
            <MaterialIcons name="inbox" size={40} color={colors.border} />
            <Text style={styles.emptyText}>No academies found</Text>
          </View>
        )}

        {(data?.perAcademy ?? []).map((a, i) => {
          const rev = a.players * PRICE_PER_PLAYER;
          return (
            <View key={a.id} style={styles.academyRow}>
              <View style={styles.academyNum}>
                <Text style={styles.academyNumText}>{i + 1}</Text>
              </View>
              <View style={{ flex: 1 }}>
                <Text style={styles.academyName}>{a.name}</Text>
                <View style={styles.academyMeta}>
                  <View style={styles.metaBadge}>
                    <MaterialIcons name="people" size={11} color={colors.primary} />
                    <Text style={styles.metaBadgeText}>{a.players} Players</Text>
                  </View>
                  <View style={styles.metaBadge}>
                    <MaterialIcons name="sports" size={11} color={colors.warning} />
                    <Text style={[styles.metaBadgeText, { color: colors.warning }]}>{a.coaches} Coaches</Text>
                  </View>
                </View>
              </View>
              <View style={styles.academyRevenue}>
                <Text style={styles.academyRevenueAmount}>{CURRENCY_SYMBOL}{formatNumber(rev)}</Text>
                <Text style={styles.academyRevenueSub}>{CURRENCY}</Text>
              </View>
            </View>
          );
        })}

        {/* Export Note */}
        <Pressable style={styles.exportBtn} onPress={handleShare}>
          <MaterialIcons name="ios-share" size={18} color={colors.textLight} />
          <Text style={styles.exportBtnText}>Share / Export Report</Text>
        </Pressable>

        <Text style={styles.footerNote}>
          Prices shown are {CURRENCY_SYMBOL}{formatNumber(PRICE_PER_PLAYER)} {CURRENCY} per player/month.{'\n'}
          Pull to refresh for the latest counts.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: spacing.md, paddingVertical: spacing.md,
    backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  backBtn: { width: 40, height: 40, justifyContent: 'center' },
  headerTitle: { ...typography.h4, color: colors.text, fontWeight: '700', flex: 1 },
  shareBtn: { width: 40, height: 40, justifyContent: 'center', alignItems: 'flex-end' },
  scroll: { flex: 1 },
  scrollContent: { padding: spacing.md, paddingBottom: 60, gap: spacing.md },

  periodBanner: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6,
    backgroundColor: colors.primaryDark, borderRadius: borderRadius.md,
    paddingVertical: spacing.sm, paddingHorizontal: spacing.md,
  },
  periodText: { fontSize: 14, fontWeight: '700', color: colors.textLight },

  revenueCard: {
    backgroundColor: colors.primary, borderRadius: borderRadius.xl,
    padding: spacing.xl, alignItems: 'center',
    shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 12, elevation: 8,
  },
  revenueLabel: { fontSize: 13, color: 'rgba(255,255,255,0.8)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  revenueAmount: { fontSize: 42, fontWeight: '900', color: colors.textLight, letterSpacing: -1, marginTop: 4 },
  revenueSub: { fontSize: 13, color: 'rgba(255,255,255,0.7)', marginTop: 2 },
  revenueDivider: { width: '60%', height: 1, backgroundColor: 'rgba(255,255,255,0.25)', marginVertical: spacing.md },
  revenueFormula: {},
  revenueFormulaText: { fontSize: 14, color: 'rgba(255,255,255,0.85)', fontWeight: '600' },

  statsRow: { flexDirection: 'row', gap: spacing.sm },
  statCard: {
    flex: 1, borderRadius: borderRadius.lg, padding: spacing.md,
    alignItems: 'center', gap: 4,
  },
  statNumber: { fontSize: 28, fontWeight: '900' },
  statLabel: { fontSize: 11, color: colors.textSecondary, fontWeight: '600', textAlign: 'center', lineHeight: 14 },

  lockCard: {
    flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-start',
    backgroundColor: colors.primary + '10', borderRadius: borderRadius.lg,
    padding: spacing.md, borderWidth: 1, borderColor: colors.primary + '30',
  },
  lockTitle: { fontSize: 13, fontWeight: '800', color: colors.text, marginBottom: 3 },
  lockSub: { fontSize: 12, color: colors.textSecondary, lineHeight: 17 },

  sectionHeader: {
    flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing.xs,
  },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: colors.text },

  emptyCard: {
    alignItems: 'center', paddingVertical: 40, gap: spacing.sm,
    backgroundColor: colors.surface, borderRadius: borderRadius.lg,
    borderWidth: 1, borderColor: colors.border,
  },
  emptyText: { fontSize: 14, color: colors.textSecondary },

  academyRow: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.md,
    backgroundColor: colors.surface, borderRadius: borderRadius.lg,
    padding: spacing.md, borderWidth: 1, borderColor: colors.border,
  },
  academyNum: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: colors.primary + '20', justifyContent: 'center', alignItems: 'center',
  },
  academyNumText: { fontSize: 13, fontWeight: '900', color: colors.primary },
  academyName: { fontSize: 14, fontWeight: '700', color: colors.text, marginBottom: 4 },
  academyMeta: { flexDirection: 'row', gap: 6 },
  metaBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 3,
    backgroundColor: colors.primary + '12', paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: borderRadius.sm,
  },
  metaBadgeText: { fontSize: 10, fontWeight: '700', color: colors.primary },
  academyRevenue: { alignItems: 'flex-end' },
  academyRevenueAmount: { fontSize: 16, fontWeight: '900', color: colors.success },
  academyRevenueSub: { fontSize: 10, color: colors.textSecondary, fontWeight: '600' },

  exportBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm,
    backgroundColor: colors.primaryDark, paddingVertical: spacing.md, borderRadius: borderRadius.md,
    marginTop: spacing.sm,
  },
  exportBtnText: { fontSize: 15, fontWeight: '700', color: colors.textLight },

  footerNote: {
    fontSize: 12, color: colors.textSecondary, textAlign: 'center', lineHeight: 18,
  },
});
